In [833]:
import numpy as np

In [834]:
a=np.array([10,7,20,12,75,15,9,18,4,12,8,14])

In [835]:
#平均数
a_mean=np.mean(a)
a_mean

17.0

In [836]:
#中位数
a_media=np.median(a)
a_media

12.0

In [837]:
#众数
counts = np.bincount(a)
a_zhong=np.argmax(counts)
a_zhong

12

In [838]:
#标准差
a_std=np.std(a)
a_std

18.027756377319946

In [839]:
from sklearn import preprocessing

In [840]:
a=a.reshape(-1,1)

In [841]:
#进行min-max规范化
min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler.fit(a.astype(float))
a_minmax = min_max_scaler.transform(a.astype(float))
a_minmax

array([[0.08450704],
       [0.04225352],
       [0.22535211],
       [0.11267606],
       [1.        ],
       [0.15492958],
       [0.07042254],
       [0.1971831 ],
       [0.        ],
       [0.11267606],
       [0.05633803],
       [0.14084507]])

In [842]:
#20美元的min-max规范化价格
print(a_minmax[2])

[0.22535211]


In [843]:
#中列数
np.max(a)/2+np.min(a)/2

39.5

In [844]:
import pandas as pd
a=pd.DataFrame(a)

In [845]:
#Z-score标准化价格
a_scaled = preprocessing.scale(a)
a_scaled 

array([[-0.38829014],
       [-0.5547002 ],
       [ 0.16641006],
       [-0.2773501 ],
       [ 3.21726114],
       [-0.11094004],
       [-0.44376016],
       [ 0.05547002],
       [-0.72111026],
       [-0.2773501 ],
       [-0.49923018],
       [-0.16641006]])

In [846]:
#20美元的Z-score标准化价格
print(a_scaled[2])

[0.16641006]


In [847]:
df1=a/10**np.ceil(np.log10(a.abs().max()))
df1

0
0   0.10
1   0.07
2   0.20
3   0.12
4   0.75
5   0.15
6   0.09
7   0.18
8   0.04
9   0.12
10  0.08
11  0.14

In [848]:
#20美元的小数标规范化价格
print(df1.loc[2])

0    0.2
Name: 2, dtype: float64


In [849]:
#倾斜度计算
a_qing=3*(a_mean-a_media)/a_std
a_qing

0.8320502943378437

In [850]:
#离群值认为是75，用Z-score的方法验证是不是该值
print(a_scaled[4])
if  a_scaled[4] < -3 or a_scaled[4] > 3:
    print("75是离群值")
else:
    print("75不是离群值")

[3.21726114]
75是离群值


In [851]:
#用IQR的方法计算是否为离散值，先求Q1和Q3
np.percentile(a, (25, 50, 75), interpolation='midpoint')

array([ 8.5, 12. , 16.5])

In [852]:
#得到Q1,Q3进行计算
Q1=8.5
Q3=16.5
IQR=Q3-Q1
x=Q1-IQR
y=Q3+IQR
print("IQR=%f"%IQR)
print("Q1-IQR=%f"%x)
print("Q3+IQR=%f"%y)
if  75<Q1-IQR or 75>Q3-IQR:
    print("75是离群值")
else:
    print("75不是离群值")

IQR=8.000000
Q1-IQR=0.500000
Q3+IQR=24.500000
75是离群值


In [853]:
#使用Z-score方法识别所有可能的离群值
i=0
for i in range(12):
    if  a_scaled[i] < -3 or a_scaled[i] > 3:
        print("该项是离群值")
    else:
        print("该项不是离群值")
    i=i+1

该项不是离群值
该项不是离群值
该项不是离群值
该项不是离群值
该项是离群值
该项不是离群值
该项不是离群值
该项不是离群值
该项不是离群值
该项不是离群值
该项不是离群值
该项不是离群值


In [854]:
#使用IQR方法识别所有可能的离群值
j=0
for j in range(12):
    if  a.values[j]<0.5 or a.values[j]>24.5:
        print("该值是离群值")
    else:
        print("该值不是离群值")
    j=j+1

该值不是离群值
该值不是离群值
该值不是离群值
该值不是离群值
该值是离群值
该值不是离群值
该值不是离群值
该值不是离群值
该值不是离群值
该值不是离群值
该值不是离群值
该值不是离群值


In [855]:
#26(a)
a1=np.array([10,7,20,12,15,9,18,4,12,8,14])
a1_mean=np.mean(a1)#去除离散值以后的均值
print("%f"%a1_mean)
a1_media=np.median(a1)#去除离散值以后的中位值
print("%f"%a1_media)

11.727273
12.000000
